### PR TITLE
Make counter-type regulators work

### LINKED ISSUE #8: Regulators leak capacity
(Using version `0.2.1` on OTP 21.)

Under overload situations, regulator capacity will leak and the system will drive itself into an unrecoverable situation, where every request to run gets denied even though nothing else is running.

To illustrate, here's the setup [[leaky_regulator.config.txt](https://github.com/lrascao/raterl/files/4083397/leaky_regulator.config.txt)] of a regulator with capacity set to `1`.
1) launch shell with `rebar3 shell --apps raterl --config leaky_regulator.config.txt`
2) then execute the following steps within it:
```erlang
% allocate single regulator slot to `Pid`
Pid = spawn(fun () -> raterl:run(login_requests, {counter, max_concurrent_logins}, fun () -> receive _ -> ok end end) end).

% confirm there are no free slots
limit_reached = raterl:run(login_requests, {counter, max_concurrent_logins}, fun () -> ok end).

% liberate the single occupied slot
Pid ! goodbye.

% verify that the regulator is now broken
limit_reached = raterl:run(login_requests, {counter, max_concurrent_logins}, fun () -> ok end).
```

Why does this happen? It happens because, while the shared ETS counter is initialized to `capacity + 1`, and the boundary condition of unavailability set to `0`, the second invocation of `raterl:run/3` in the demo above made the counter value inadvertently go from `1` to `0`, and this permanently tainted the regulator.

I believe it's possible to adjust the boundary condition checks to fix this, but it might become needlessly complex - and it still doesn't solve the issue of processes being brutally killed while they're taking up regulator capacity, since those slots will also be permanently lost.

My suggestion would be to not use shared ETS at all, and instead rely on a single `gen_server` (or suchlike) that's responsible for enforcing the concurrency limit and monitoring the processes taking up capacity in order to ensure there are no leaks. If you agree, I might do a PR this week.

### PR DESCRIPTION
**Pull request by g-andrade**
Move the accounting of slots to the associated `raterl_queue` processes and monitor slot owners in order to ensure that even brutally killed processes free up any slots they might have been using.

(Keep using ETS for rate-type regulators, however.)

Closes #8 .

### CODE REVIEW

**Comment by g-andrade** [comment]
I've taken the liberty of removing the Travis target for OTP 17, since not even `rebar3` can run on it nowadays.

File: src/raterl_utils.erl [hunk 1]
```diff
@@ -39,6 +40,21 @@ queue_name(Name) ->
     list_to_atom("raterl_" ++
                  atom_to_list(Name)).
 
+-ifdef(NO_MAPS_TAKE).
```
Comment (lrascao) [inline src/raterl_utils.erl:43]: this is no longer since 17 support got dropped right?

**Review by lrascao — CHANGES_REQUESTED** [review]

**Comment by g-andrade** [comment]
OTP 18 requires it, unfortunately.

**Comment by lrascao** [comment]
right
